// 크롤링봇과 연관있음 -> 무슨연관이지? 찾아봐
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <na>
          <span>layout</span>
        </na>
        {children}
      </body>
    </html>
  );
}
